"""PDF report builder — letter size, Helvetica, B&W, no branding."""

from __future__ import annotations

import logging
import re
from datetime import datetime
from pathlib import Path
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    BaseDocTemplate, Frame, PageBreak, PageTemplate, Paragraph, Spacer,
    Table, TableStyle,
)

from engine.checks.base import display_column

logger = logging.getLogger(__name__)

CHECK_LABELS: dict[str, str] = {
    # completeness
    "missing_values":               "Missing values",
    "empty_rows":                   "Empty rows",
    "null_concentration":           "Null concentration",
    # uniqueness
    "duplicate_rows":               "Duplicate rows",
    "duplicate_keys_inferred":      "Inferred duplicate keys",
    "duplicate_column_combos":      "Duplicate column value combinations",
    # validity
    "mixed_types":                  "Mixed data types",
    "invalid_dates":                "Invalid date values",
    "malformed_identifiers":        "Malformed identifiers",
    # range
    "future_dates":                 "Future-dated values",
    "impossible_values":            "Impossible / out-of-range values",
    # format
    "format_inconsistency_name_as_value":    "Column name appears as value",
    "format_inconsistency_numeric_as_text":  "Numeric values stored as text",
    "format_inconsistency_date_mixed":       "Mixed date / non-date strings",
    "casing_inconsistency":         "Inconsistent casing",
    "whitespace_issues":            "Leading / trailing whitespace",
    # consistency
    "id_to_name_conflicts":         "ID-to-name mapping conflicts",
    # distribution
    "outliers":                     "Statistical outliers",
    "value_concentration":          "Suspicious value concentration",
    # cross-field
    "start_after_end":              "Start date after end date",
    # schema
    "schema_missing_column":            "Missing required column",
    "schema_unexpected_columns":        "Unexpected column (not in schema)",
    "schema_type_mismatch_numeric":     "Type mismatch (expected numeric)",
    "schema_type_mismatch_date":        "Type mismatch (expected date)",
    "schema_type_mismatch_text":        "Type mismatch (expected text)",
    "schema_type_mismatch_identifier":  "Type mismatch (expected identifier)",
    "schema_below_min":                 "Value below minimum threshold",
    "schema_above_max":                 "Value above maximum threshold",
    "schema_format_violation":          "Format violation (regex)",
}


def generate_pdf(
    metadata: dict[str, Any],
    check_results: list[dict[str, Any]],
    narrative: str,
    output_path: str | Path,
) -> str:
    """Generate a multi-page audit PDF at `output_path`. Returns the path as str."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    doc = BaseDocTemplate(
        str(path),
        pagesize=LETTER,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch,
        topMargin=0.75 * inch, bottomMargin=0.9 * inch,
        title="AuditIQ Data Quality Report",
        author="AuditIQ",
    )
    frame = Frame(
        doc.leftMargin, doc.bottomMargin, doc.width, doc.height, id="body",
    )
    doc.addPageTemplates([PageTemplate(id="audit", frames=frame, onPage=_draw_footer)])

    story: list[Any] = []
    story.extend(_cover_page(metadata))
    story.append(PageBreak())
    story.extend(_summary_section(check_results))
    story.append(Spacer(1, 0.25 * inch))
    story.extend(_narrative_section(narrative))

    doc.build(story)
    logger.info("PDF written to %s", path)
    return str(path)


def _draw_footer(canvas, doc) -> None:
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    canvas.setFillColor(colors.grey)
    canvas.drawCentredString(
        LETTER[0] / 2,
        0.5 * inch,
        f"Generated by AuditIQ  |  {ts}  |  Page {doc.page}",
    )
    canvas.restoreState()


def _cover_page(metadata: dict[str, Any]) -> list[Any]:
    styles = _styles()
    audit_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    rows = metadata.get("rows", 0) or 0
    cols = metadata.get("columns", 0) or 0
    elements: list[Any] = [
        Spacer(1, 2.2 * inch),
        Paragraph("Data Quality Audit Report", styles["title"]),
        Spacer(1, 0.5 * inch),
        Paragraph(f"<b>File:</b> {metadata.get('filename', 'n/a')}", styles["cover_body"]),
        Paragraph(f"<b>Rows:</b> {rows:,}", styles["cover_body"]),
        Paragraph(f"<b>Columns:</b> {cols:,}", styles["cover_body"]),
        Paragraph(f"<b>Audit date/time:</b> {audit_time}", styles["cover_body"]),
    ]
    sheet_name = metadata.get("sheet_name")
    if sheet_name:
        elements.append(Paragraph(f"<b>Sheet:</b> {sheet_name}", styles["cover_body"]))
    return elements


def _summary_section(check_results: list[dict[str, Any]]) -> list[Any]:
    styles = _styles()
    non_zero = [r for r in check_results if (r.get("count") or 0) > 0]
    elements: list[Any] = [
        Paragraph("Section A — Summary of Findings", styles["section"]),
        Spacer(1, 0.1 * inch),
    ]
    if not non_zero:
        elements.append(
            Paragraph("No data quality issues were detected.", styles["body"])
        )
        return elements

    data: list[list[str]] = [["Column Name", "Issue Type", "Affected Records", "% of Total"]]
    for r in non_zero:
        col = display_column(r)
        issue = CHECK_LABELS.get(r.get("check", ""), r.get("check", "unknown"))
        count = r.get("count") or 0
        total = r.get("total") or 0
        pct = f"{(count / total * 100):.2f}%" if total else "-"
        data.append([str(col), issue, f"{count:,}", pct])

    table = Table(
        data,
        colWidths=[1.7 * inch, 2.6 * inch, 1.25 * inch, 0.95 * inch],
        repeatRows=1,
    )
    style = TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BACKGROUND", (0, 0), (-1, 0), colors.black),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("ALIGN", (2, 1), (3, -1), "RIGHT"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.black),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.grey),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ])
    for idx in range(1, len(data)):
        if idx % 2 == 0:
            style.add("BACKGROUND", (0, idx), (-1, idx), colors.whitesmoke)
    table.setStyle(style)
    elements.append(table)
    return elements


def _narrative_section(narrative: str) -> list[Any]:
    styles = _styles()
    elements: list[Any] = [
        Paragraph("Section B — Detailed Narrative", styles["section"]),
        Spacer(1, 0.1 * inch),
    ]
    if not narrative or not narrative.strip():
        elements.append(
            Paragraph("No narrative was generated for this report.", styles["body"])
        )
        return elements

    paragraphs = [p.strip() for p in re.split(r"\n\s*\n", narrative.strip()) if p.strip()]
    for paragraph in paragraphs:
        elements.append(Paragraph(_format_paragraph(paragraph), styles["body"]))
        elements.append(Spacer(1, 0.12 * inch))
    return elements


def _format_paragraph(text: str) -> str:
    """Escape markup and bold a leading column heading if a separator is present."""
    safe = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    safe = re.sub(r"\s+", " ", safe)
    match = re.match(r"^([A-Z][^.!?]{0,60}?)([:\-\u2013\u2014])\s+(.*)", safe)
    if match:
        heading, sep, rest = match.groups()
        return f"<b>{heading}</b>{sep} {rest}"
    return safe


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "Title",
            parent=base["Title"],
            fontName="Helvetica-Bold",
            fontSize=24,
            leading=30,
            alignment=TA_CENTER,
            textColor=colors.black,
        ),
        "cover_body": ParagraphStyle(
            "CoverBody",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=12,
            leading=18,
            alignment=TA_CENTER,
        ),
        "section": ParagraphStyle(
            "Section",
            parent=base["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=14,
            leading=18,
            spaceAfter=6,
            alignment=TA_LEFT,
            textColor=colors.black,
        ),
        "body": ParagraphStyle(
            "Body",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            alignment=TA_JUSTIFY,
        ),
    }
